---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: target-app-test-nc
  labels:
    app: target-app-test-nc
    chaldeploy-target: "yes"
spec:
  replicas: 1
  selector:
    matchLabels:
      app: target-app-test-nc
  template:
    metadata:
      labels:
        app: target-app-test-nc
    spec:
      containers:
      - name: target-app-test-nc
        image: test-nc:v2
        ports:
        - containerPort: 31337
        resources:
          limits:
            cpu: "500m"
            memory: "256Mi"
        imagePullPolicy: Never
---
apiVersion: v1
kind: Service
metadata:
  name: target-app-test-nc
spec:
  ports:
  - port: 31337
    targetPort: 31337
    protocol: TCP
  selector:
    app: target-app-test-nc
  type: NodePort 
 